---
title: "Data Wrangling for Elephant Seal Animation"
author: "Jessica Kendall-Bar"
date: "2/7/2021"
output:
  pdf_document: default
  html_document: default
---

```{r include = FALSE}
library(here)
library(lubridate)
library(tidyr)
library(dplyr)
library(ggplot2)
```

## Elephant Seal Animation Data Wrangling

This `RMarkdown` document explains the steps to get the Heart Rate and Stroke data into a format for use in After Effects.

```{r Load in data}
HR_data  <- read.csv(here("data","Glacier_HR.csv"))
Depth_data <- read.csv(here("data","Glacier_Dep.csv"))
Accel_data <- read.csv(here("data","Glacier_Ac.csv")) #Acceleration data is in 16Hz
#all_data   <- read.csv(here("data","MA18_099_16A0746-Archive.csv"))
```

```{r pre-process data}
HR_data$R.Time <- as.POSIXct(HR_data$ExDateTime, origin = "1899-12-30")
HR_data$Seconds <- as.numeric(HR_data$R.Time-HR_data$R.Time[1])

minHR <- min(HR_data$InHR)
idx <- match(minHR, HR_data$InHR)
minHR_R.Time <- HR_data$R.Time[idx]
minHR_Seconds <- HR_data$Seconds[idx]
  
#This shows how long the data set is.
print(HR_data$R.Time[nrow(HR_data)]-HR_data$R.Time[1])
paste("The lowest heartrate was",min(HR_data$InHR),"which occurred at", minHR_R.Time, "at", minHR_Seconds)
```

## Inspecting the data

Previewing the dataset and inspecting each element.

```{r echo=FALSE}
# Preview the dataset and the class types
head(HR_data,10)
```
```{r pressure, echo=FALSE}
# Subsetting data around disturbance dives identified in labchart
# startsec <- 28320
# endsec   <- 31080

#Indices based on minHR:
# startsec <- 95000
# endsec   <- 96000

#Indices based on labchart 1st disturbance
startsec <- 40000
endsec   <- 42000


fs <- 25

HR_subset <- HR_data %>% filter(Seconds > startsec) %>% filter(Seconds<endsec)

for (i in 1:nrow(HR_subset)) {
  HR_subset$Interval[i] <- HR_subset$Seconds[i+1] - HR_subset$Seconds[i]
}
HR_subset <- na.omit(HR_subset)
paste("Shortest interbeat interval is ", min(HR_subset$Interval))
paste("Longest interbeat interval is ", max(HR_subset$Interval))

HR_subset$Wait <- HR_subset$Interval - 0.30

# Putting data into new R object where HR data will be put in a single vector
HR_subset$New_Row_Index <- round(HR_subset$Seconds*fs)
size <- max(HR_subset$New_Row_Index)
HR <- data.frame(rep(0,(endsec-startsec)*fs))
colnames(HR) <- c("binary")

# to create binary version of data, not being used and not returning good values right now
# index <- 0
# for (i in 1:nrow(HR_subset)) {
#   index[i] <- HR_subset$New_Row_Index[i]
#   HR$binary[index[i]] = 1
# }
```

```{r}
#Write csv file - use this CSV to import annotations into EDF file
write.table(t(HR$binary), here("data","HR_data_for_AE.txt"), sep = "", col.names = FALSE, row.names = FALSE)
write.csv(HR_subset$Seconds, here("data", "HR_subset_for_Reaper.csv"), sep=",")
write.csv(HR_subset$Interval, here("data", "HR_data_for_Python.csv"), sep=",", col.names = TRUE, row.names = FALSE)
write.csv(HR_subset$Wait, here("data","HR_wait_for_Python.csv"), sep=",", col.names = TRUE, row.names = FALSE)
```

```{r plot}
HR_forPlot <- HR_data %>% filter(Seconds > startsec) %>% filter(Seconds<endsec)

plot1 <- ggplot(HR_forPlot, aes(x=Seconds,y=InHR))+
           geom_line()+
           theme_classic()
           
plot1+labs(
  title = "Instananeous HR over time (bpm)",
  x= "Time (seconds)",
  y= "Instantaneous HR (bpm)",
  caption = "Figure by Jessica Kendall-Bar"
)
```

```{r}
HR_forPlot <- HR_data %>% filter(Seconds > startsec) %>% filter(Seconds<endsec)

plot1 <- ggplot(HR_forPlot, aes(x=Seconds,y=InHR))+
           geom_line()+
           theme_classic()
           
plot1+labs(
  title = "Instananeous HR over time (bpm)",
  x= "Time (seconds)",
  y= "Instantaneous HR (bpm)",
  caption = "Figure by Jessica Kendall-Bar"
)
```